-- Migration 012: Seed default email templates for transactional emails
-- These are the default templates used when no custom template exists.
-- The admin can modify these through the admin panel.

INSERT INTO email_templates (id, aid, name, subject, template_type, body, html_body, is_html, is_default)
VALUES
(
    '00000000-0000-0000-0000-000000000001',
    '00000000-0000-0000-0000-000000000000',
    'Welcome Email',
    'Welcome to WorkflowSwift!',
    'welcome',
    E'Hello {{name}},\n\nWelcome to WorkflowSwift! Your account has been created successfully.\n\nHere are your login credentials:\n  Email: {{email}}\n  Temporary Password: {{password}}\n\nPlease log in at {{app_url}} and change your password as soon as possible.\n\nBest regards,\nThe WorkflowSwift Team',
    E'<!DOCTYPE html>\n<html>\n<head><meta charset="utf-8"></head>\n<body style="font-family: Arial, sans-serif; line-height: 1.6; color: #333; margin: 0; padding: 0; background-color: #f4f4f4;">\n  <table role="presentation" style="width: 100%; max-width: 600px; margin: 0 auto; background-color: #ffffff; border-radius: 8px; overflow: hidden; margin-top: 20px; margin-bottom: 20px;">\n    <tr>\n      <td style="padding: 30px 40px; background: linear-gradient(135deg, #2563eb 0%, #1d4ed8 100%); text-align: center;">\n        <h1 style="color: #ffffff; font-size: 28px; margin: 0;">Welcome to WorkflowSwift!</h1>\n      </td>\n    </tr>\n    <tr>\n      <td style="padding: 40px;">\n        <p style="font-size: 16px; color: #374151;">Hello <strong>{{name}}</strong>,</p>\n        <p style="font-size: 16px; color: #374151; line-height: 1.6;">Welcome to WorkflowSwift! Your account has been created successfully. You can now start automating your workflows and managing your projects with ease.</p>\n        <div style="background: #f3f4f6; padding: 20px; border-radius: 8px; margin: 25px 0; border-left: 4px solid #2563eb;">\n          <p style="margin: 8px 0; font-size: 14px; color: #6b7280;"><strong>Email:</strong> <span style="color: #111827;">{{email}}</span></p>\n          <p style="margin: 8px 0; font-size: 14px; color: #6b7280;"><strong>Temporary Password:</strong> <span style="color: #111827; font-family: monospace;">{{password}}</span></p>\n        </div>\n        <p style="font-size: 14px; color: #6b7280;">Please log in and change your password as soon as possible for security.</p>\n        <table role="presentation" style="margin: 30px auto;">\n          <tr>\n            <td style="background: #2563eb; border-radius: 6px; text-align: center; padding: 0;">\n              <a href="{{app_url}}" style="display: inline-block; padding: 14px 40px; color: #ffffff; text-decoration: none; font-size: 16px; font-weight: bold; border-radius: 6px;">Log In Now</a>\n            </td>\n          </tr>\n        </table>\n        <hr style="border: none; border-top: 1px solid #e5e7eb; margin: 30px 0;">\n        <p style="font-size: 14px; color: #9ca3af; text-align: center; line-height: 1.4;">\n          Need help? Contact us at <a href="mailto:support@workflowswift.com" style="color: #2563eb; text-decoration: none;">support@workflowswift.com</a>\n        </p>\n        <p style="font-size: 14px; color: #9ca3af; text-align: center; margin-top: 20px;">\n          Best regards,<br>\n          <strong style="color: #374151;">The WorkflowSwift Team</strong>\n        </p>\n      </td>\n    </tr>\n  </table>\n</body>\n</html>',
    true,
    true
),
(
    '00000000-0000-0000-0000-000000000002',
    '00000000-0000-0000-0000-000000000000',
    'Team Invite',
    'You have been invited to join {{account_name}} on WorkflowSwift',
    'team_invite',
    E'Hello {{name}},\n\nYou have been invited to join {{account_name}} on WorkflowSwift!\n\nHere are your login credentials:\n  Email: {{email}}\n  Temporary Password: {{password}}\n\nPlease log in at {{app_url}} and change your password as soon as possible.\n\nBest regards,\nThe WorkflowSwift Team',
    E'<!DOCTYPE html>\n<html>\n<head><meta charset="utf-8"></head>\n<body style="font-family: Arial, sans-serif; line-height: 1.6; color: #333; margin: 0; padding: 0; background-color: #f4f4f4;">\n  <table role="presentation" style="width: 100%; max-width: 600px; margin: 0 auto; background-color: #ffffff; border-radius: 8px; overflow: hidden; margin-top: 20px; margin-bottom: 20px;">\n    <tr>\n      <td style="padding: 30px 40px; background: linear-gradient(135deg, #059669 0%, #047857 100%); text-align: center;">\n        <h1 style="color: #ffffff; font-size: 28px; margin: 0;">Team Invitation</h1>\n      </td>\n    </tr>\n    <tr>\n      <td style="padding: 40px;">\n        <p style="font-size: 16px; color: #374151;">Hello <strong>{{name}}</strong>,</p>\n        <p style="font-size: 16px; color: #374151;">You have been invited to join <strong>{{account_name}}</strong> on WorkflowSwift!</p>\n        <div style="background: #f3f4f6; padding: 20px; border-radius: 8px; margin: 25px 0; border-left: 4px solid #059669;">\n          <p style="margin: 8px 0; font-size: 14px; color: #6b7280;"><strong>Email:</strong> <span style="color: #111827;">{{email}}</span></p>\n          <p style="margin: 8px 0; font-size: 14px; color: #6b7280;"><strong>Temporary Password:</strong> <span style="color: #111827; font-family: monospace;">{{password}}</span></p>\n        </div>\n        <p style="font-size: 14px; color: #6b7280;">Please log in and change your password as soon as possible.</p>\n        <table role="presentation" style="margin: 30px auto;">\n          <tr>\n            <td style="background: #059669; border-radius: 6px; text-align: center; padding: 0;">\n              <a href="{{app_url}}" style="display: inline-block; padding: 14px 40px; color: #ffffff; text-decoration: none; font-size: 16px; font-weight: bold; border-radius: 6px;">Log In Now</a>\n            </td>\n          </tr>\n        </table>\n        <hr style="border: none; border-top: 1px solid #e5e7eb; margin: 30px 0;">\n        <p style="font-size: 14px; color: #9ca3af; text-align: center; line-height: 1.4;">\n          Questions? Reach out to your team admin at <a href="mailto:support@workflowswift.com" style="color: #059669; text-decoration: none;">support@workflowswift.com</a>\n        </p>\n        <p style="font-size: 14px; color: #9ca3af; text-align: center; margin-top: 20px;">\n          Best regards,<br>\n          <strong style="color: #374151;">The WorkflowSwift Team</strong>\n        </p>\n      </td>\n    </tr>\n  </table>\n</body>\n</html>',
    true,
    true
),
(
    '00000000-0000-0000-0000-000000000003',
    '00000000-0000-0000-0000-000000000000',
    'Password Reset',
    'Password Reset Request',
    'password_reset',
    E'Your password reset code is: {{token}}\n\nThis code expires in 1 hour.\n\nIf you did not request this password reset, please ignore this email.\n\n- The WorkflowSwift Team',
    E'<!DOCTYPE html>\n<html>\n<head><meta charset="utf-8"></head>\n<body style="font-family: Arial, sans-serif; line-height: 1.6; color: #333; margin: 0; padding: 0; background-color: #f4f4f4;">\n  <table role="presentation" style="width: 100%; max-width: 600px; margin: 0 auto; background-color: #ffffff; border-radius: 8px; overflow: hidden; margin-top: 20px; margin-bottom: 20px;">\n    <tr>\n      <td style="padding: 30px 40px; background: linear-gradient(135deg, #dc2626 0%, #b91c1c 100%); text-align: center;">\n        <h1 style="color: #ffffff; font-size: 28px; margin: 0;">Password Reset</h1>\n      </td>\n    </tr>\n    <tr>\n      <td style="padding: 40px;">\n        <p style="font-size: 16px; color: #374151;">You have requested a password reset.</p>\n        <div style="background: #fef2f2; padding: 20px; border-radius: 8px; margin: 25px 0; text-align: center; border: 2px dashed #dc2626;">\n          <p style="font-size: 32px; font-weight: bold; letter-spacing: 6px; color: #dc2626; margin: 0; font-family: monospace;">{{token}}</p>\n        </div>\n        <p style="font-size: 14px; color: #6b7280;">This code expires in <strong>1 hour</strong>.</p>\n        <p style="font-size: 14px; color: #9ca3af; margin-top: 25px;">If you did not request this password reset, please ignore this email.</p>\n        <hr style="border: none; border-top: 1px solid #e5e7eb; margin: 30px 0;">\n        <p style="font-size: 14px; color: #9ca3af; text-align: center;">\n          - The WorkflowSwift Team\n        </p>\n      </td>\n    </tr>\n  </table>\n</body>\n</html>',
    true,
    true
)
ON CONFLICT (id) DO NOTHING;
