-- 021: template categories with icons — NEUTRALISED (card t_4ebd6f98)
--
-- This file used to `ALTER TABLE template_categories ADD COLUMN icon` and upsert THIRTEEN *sector*
-- categories (sales-lead-gen, service-businesses, recruitment-staffing, marketing-agencies,
-- professional-services, ecommerce-retail, healthcare-wellness, construction-development,
-- grant-funding, education-training, publishing-media, site-flipping, government-contracting).
--
-- It is neutralised for the same two reasons as 019, and 023 was neutralised before it for exactly
-- this class:
--   1. `template_categories` was created by NO migration (measured: `grep -rn "CREATE TABLE.*
--      template_categories" migrations/` = 0 hits), so on a fresh or restored database both
--      statements raised `42P01`, and per src/db.rs an unrecorded failure is FATAL — the service
--      refused to boot. The table and its `icon` column now come from
--      000_baseline_live_schema.sql.
--   2. The 13 rows are a SECTOR vocabulary, while `template_categories.slug` IS this platform's
--      INDUSTRY vocabulary: GET /api/v1/industries serves that table as the industry picker
--      (src/handlers/industry_handler.rs:18) and every consumer compares against its slug
--      (plan_capabilities.industry_slug, account_industries.industry_slug, the served SPA's
--      `t.category === <industry slug>`). Seeding sectors there offers bogus industry choices —
--      card t_9f7083b0 (migration 061) already decided the industry vocabulary wins.
--      The six industries the platform ships are seeded by 000a_industry_vocabulary.sql, exactly
--      the six rows production serves (measured 2026-09-25: 6 rows in template_categories, 6 in
--      industries, same slugs).
--
-- PRODUCTION: the file is recorded in `_migrations` (2026-08-09) and skipped at boot, so this edit
-- cannot change the live database — it only stops a fresh build from resurrecting 13 sector rows
-- that production does not have. Deliberately comment-only: it must stay a clean, recordable batch.
